# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DVox9bF5cNykYR-w2lb65_Llf8L5q0zt
"""

import pandas as pd
import math

def find_entropy(dataset):
    for col in dataset.columns:
        count = dataset[col].value_counts()
        prob = count / len(dataset)
        entropy = -(prob * prob.apply(math.log)).sum()
        print(f'Entropy for {col}: {entropy}')

# Load your dataset
dataset = pd.read_csv('CAR





  l.csv')

# Calculate and print the entropy for each column
find_entropy(dataset)